### ISSUE TITLE
`/templates/` changed to `/ctr-tmps/` in the code but not updated in README.md

### ISSUE THREAD

**Issue by na399** [heekei/code-template-replace#1]
Hi @heekei!

Thanks for developing this nice little tool that can easily be used by my peers who are non-developers. 

I've just realised `/templates/` was changed to `/ctr-tmps/` in the code but it was not updated in `README.md`. It might be for a reason that I'm not aware of. 

Could you change any of them to make it consistent, please?

Thanks!

**Comment by heekei** [comment]
thanks for using. I'll update as soon as posible.

**Comment by na399** [comment]
Thanks a lot. I'll publish a guide on to make use of your tool. I'll let you know once published.

**Comment by heekei** [comment]
Developed a gulp plugin that may be useful to you.
[](https://github.com/heekei/gulp-code-replace)

**Comment by heekei** [comment]
Developed a gulp plugin that may be useful to you.
[https://github.com/heekei/gulp-code-replace](https://github.com/heekei/gulp-code-replace)

**Comment by na399** [comment]
Awesome! 👏 
I thought about making it myself. Your superb work will help me and my peers a lot.  
Words are not enough to express my thanks. 🙏
